name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 */12 * * *"  # Roda a cada 12 horas
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: GhosTSparta1
          outputs: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: output  # Publica na branch "output"
          folder: dist